import assert from 'node:assert/strict';
import { mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { DatabaseSync } from 'node:sqlite';
import { Storage } from '@google-cloud/storage';
const root = path.resolve(process.env.DATA_DIR);
const backups = (await readdir(path.join(root,'backups'))).filter(x=>/^music-.*\.sqlite$/.test(x)).sort();
assert.ok(backups.length,'Run the backup service first');
const name=backups.at(-1);
const parent=path.join(root,'recovery-verification',randomUUID());
await mkdir(parent,{recursive:true,mode:0o700});
const downloaded=path.join(parent,'downloaded.sqlite');
await new Storage().bucket(process.env.GCS_BUCKET).file(`backups/${name}`).download({destination:downloaded});
const target=path.join(parent,'restored');
const result=spawnSync(process.execPath,['scripts/restore.mjs',downloaded,target],{encoding:'utf8'});
assert.equal(result.status,0,result.stderr);
const original=new DatabaseSync(downloaded,{readOnly:true});
const restored=new DatabaseSync(path.join(target,'music.sqlite'),{readOnly:true});
assert.equal(restored.prepare('PRAGMA integrity_check').get().integrity_check,'ok');
assert.equal(restored.prepare('SELECT count(*) AS n FROM tracks').get().n,original.prepare('SELECT count(*) AS n FROM tracks').get().n);
assert.equal(restored.prepare('SELECT count(*) AS n FROM sessions').get().n,0);
assert.equal(restored.prepare("SELECT value FROM settings WHERE key='adminHash'").get()?.value,original.prepare("SELECT value FROM settings WHERE key='adminHash'").get()?.value);
original.close();restored.close();
console.log('GCS_BACKUP_DOWNLOAD_RESTORE_INTEGRITY_ADMIN_SESSION_VERIFIED');
